---
# Junos backup config tasks
- name: Collect junos device running configs
  junipernetworks.junos.junos_command:
    commands: "show configuration"
    display: set
  register: junos_config_output