---
- name: Collect junos device running configs
  junipernetworks.junos.junos_command:
    commands: show configuration
    display: set
  register: config_output
  ignore_errors: true

# - name: Save the configuration to the temporary config store
#   ansible.builtin.copy:
#     content: "{{ config_output['stdout'] }}"
#     dest: "{{ tmp_config_store }}"
#   delegate_to: localhost


- name: Add host to failed_hosts list if the task fails
  ansible.builtin.set_fact:
    failed_hosts: "{{ failed_hosts + inventory_hostname }}"
  when: config_output.failed
  ignore_errors: true

# regex_replace('\r\n', '\n'): Ensures that the configuration is formatted properly with new lines,
# in case the original output contains carriage return and line feed (\r\n).
- name: Ensure the config is properly formatted
  ansible.builtin.set_fact:
    formatted_config: "{{ config_output.stdout[0] | regex_replace('\r\n', '\n') }}"
  delegate_to: localhost
  ignore_errors: true

- name: Save the configuration to the temporary config store
  ansible.builtin.copy:
    content: "{{ formatted_config }}"
    dest: "{{ tmp_config_store }}"
  delegate_to: localhost
  ignore_errors: true
